# Generated by Django 4.2.2 on 2023-07-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='symbol',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
